/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
/**
 *
 * @author Valéria
 */
public class ManterFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form ManterFuncionario
     */
    public ManterFuncionario() {
        initComponents();
        DefaultTableModel mode = (DefaultTableModel) tableStyle1.getModel();
        ArrayList<Piloto> pilotos = App.getPilotos();
        for(int i = 0; i < pilotos.size(); i++){
            mode.addRow(new Object[] {pilotos.get(i).getNome(), pilotos.get(i).getCpf(), pilotos.get(i).getTelefone(), pilotos.get(i).getHabilitacao()});
        }
        
        mode = (DefaultTableModel) tableStyle2.getModel();
        ArrayList<Comissario> comissarios = App.getComissarios();
        for (int i = 0; i < comissarios.size(); i++){
            mode.addRow(new Object [] {comissarios.get(i).getNome(), comissarios.get(i).getCpf(), comissarios.get(i).getTelefone(), comissarios.get(i).getIdiomas()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        myJButton1 = new MyJButton();
        myJButton2 = new MyJButton();
        myJButton3 = new MyJButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableStyle1 = new TableStyle();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        myJButton4 = new MyJButton();
        myJButton5 = new MyJButton();
        myJButton6 = new MyJButton();
        jLabel11 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableStyle2 = new TableStyle();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(0, 196, 204));

        jPanel1.setBackground(new java.awt.Color(0, 196, 204));

        jPanel3.setBackground(new java.awt.Color(207, 241, 246));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel3.setText("CPF:");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel4.setText("Telefone:");

        jTextField2.setBackground(new java.awt.Color(207, 241, 246));
        jTextField2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jPanel4.setBackground(new java.awt.Color(0, 196, 204));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Dados do Piloto");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextField5.setBackground(new java.awt.Color(207, 241, 246));
        jTextField5.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jTextField5.setCaretColor(new java.awt.Color(0, 204, 204));


        jTextField6.setBackground(new java.awt.Color(207, 241, 246));
        jTextField6.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));


        myJButton1.setText("Alterar");
        myJButton1.setCorHover(new java.awt.Color(0, 200, 142));
        myJButton1.setCorSelected(new java.awt.Color(255, 0, 0));
        myJButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        myJButton1.setRadius(20);
        myJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myJButton1ActionPerformed(evt);
            }
        });

        myJButton2.setText("Cadastrar");
        myJButton2.setActionCommand("");
        myJButton2.setCorHover(new java.awt.Color(0, 200, 142));
        myJButton2.setCorSelected(new java.awt.Color(255, 0, 0));
        myJButton2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 17)); // NOI18N
        myJButton2.setRadius(20);
        myJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myJButton2ActionPerformed(evt);
            }
        });

        myJButton3.setText("Cancelar");
        myJButton3.setCorHover(new java.awt.Color(0, 200, 142));
        myJButton3.setCorSelected(new java.awt.Color(255, 0, 0));
        myJButton3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        myJButton3.setRadius(20);
        myJButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myJButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel5.setText("Habilitação:");

        jComboBox2.setBackground(new java.awt.Color(0, 118, 128));
        jComboBox2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Piloto Privado (PP)", "Piloto Comercial (PC)", "Licença de piloto de linha aérea (PLA)" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(myJButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(myJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(myJButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField6)
                                .addComponent(jTextField5)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myJButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myJButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jPanel5.setBackground(new java.awt.Color(207, 241, 246));

        tableStyle1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Telefone", "Habilitação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableStyle1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableStyle1);

        jComboBox1.setBackground(new java.awt.Color(0, 118, 128));
        jComboBox1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buscar por", "Nome", "Cpf", "Telefone", "Habilitação" }));
        

        jTextField1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 196, 204), 2, true));
        jTextField1.setCaretColor(new java.awt.Color(0, 196, 204));
        jTextField1.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e){}
            public void insertUpdate(DocumentEvent e){
                buscarPiloto();
            }
            public void removeUpdate(DocumentEvent e){
                if(jTextField1.getText().trim().isEmpty()){
                    DefaultTableModel mode = (DefaultTableModel) tableStyle1.getModel();
                    while(mode.getRowCount() != 0){
                        mode.removeRow(0);
                    }
                    for(int i=0;i<pilotos.size();i++){
                        mode.addRow(new Object[] {pilotos.get(i).getNome(), pilotos.get(i).getCpf(), pilotos.get(i).getTelefone(), pilotos.get(i).getHabilitacao()});
                    }
                }
                else{
                    buscarPiloto();
                }
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Piloto", jPanel1);

        jPanel6.setBackground(new java.awt.Color(0, 196, 204));

        jPanel7.setBackground(new java.awt.Color(207, 241, 246));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel7.setText("Nome:");

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel8.setText("CPF:");

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel9.setText("Telefone:");

        jTextField3.setBackground(new java.awt.Color(207, 241, 246));
        jTextField3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jPanel8.setBackground(new java.awt.Color(0, 196, 204));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Dados do Comissário");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextField7.setBackground(new java.awt.Color(207, 241, 246));
        jTextField7.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jTextField7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jTextField7.setCaretColor(new java.awt.Color(0, 204, 204));


        jTextField8.setBackground(new java.awt.Color(207, 241, 246));
        jTextField8.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jTextField8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));


        myJButton4.setText("Alterar");
        myJButton4.setCorHover(new java.awt.Color(0, 200, 142));
        myJButton4.setCorSelected(new java.awt.Color(255, 0, 0));
        myJButton4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        myJButton4.setRadius(20);
        myJButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myJButton4ActionPerformed(evt);
            }
        });

        myJButton5.setText("Cadastrar");
        myJButton5.setActionCommand("");
        myJButton5.setCorHover(new java.awt.Color(0, 200, 142));
        myJButton5.setCorSelected(new java.awt.Color(255, 0, 0));
        myJButton5.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 17)); // NOI18N
        myJButton5.setRadius(20);
        myJButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myJButton5ActionPerformed(evt);
            }
        });

        myJButton6.setText("Cancelar");
        myJButton6.setCorHover(new java.awt.Color(0, 200, 142));
        myJButton6.setCorSelected(new java.awt.Color(255, 0, 0));
        myJButton6.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        myJButton6.setRadius(20);
        myJButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myJButton6ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel11.setText("Idiomas:");

        jComboBox3.setBackground(new java.awt.Color(0, 118, 128));
        jComboBox3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Português", "Inglês", "Espanhol", "Francês", "Alemão", "Aramaico", "Latim", "Japonês", "Mandarim", "Russo", "Coreano", "Italiano" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField3)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(myJButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(myJButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(myJButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(2, 2, 2)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myJButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myJButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myJButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel9.setBackground(new java.awt.Color(207, 241, 246));

        tableStyle2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Telefone", "Idiomas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableStyle2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tableStyle2);

        jComboBox4.setBackground(new java.awt.Color(0, 118, 128));
        jComboBox4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buscar por", "Nome", "Cpf", "Telefone", "Idioma" }));


        jTextField4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 196, 204), 2, true));
        jTextField4.setCaretColor(new java.awt.Color(0, 196, 204));
        jTextField4.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e){}
            public void insertUpdate(DocumentEvent e){
                buscarComissario();
            }
            public void removeUpdate(DocumentEvent e){
                if(jTextField4.getText().trim().isEmpty()){
                    DefaultTableModel mode = (DefaultTableModel) tableStyle2.getModel();
                    while(mode.getRowCount() != 0){
                        mode.removeRow(0);
                    }
                    for(int i=0;i<comissarios.size();i++){
                        mode.addRow(new Object[] {comissarios.get(i).getNome(), comissarios.get(i).getCpf(), comissarios.get(i).getTelefone(), comissarios.get(i).getIdiomas()});
                    }
                }
                else{
                    buscarComissario();
                }
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Comissários", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void myJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myJButton1ActionPerformed
        if(alterarpiloto){
            alterarpiloto = false;
            pilotos.remove(tableStyle1.getSelectedRow());
            jTextField6.setText(null); jTextField2.setText(null); jTextField5.setText(null); jComboBox2.setSelectedIndex(0);
            myJButton1.setText("ALTERAR");
            myJButton2.setText("CADASTRAR");
            DefaultTableModel model = (DefaultTableModel) tableStyle1.getModel();
            model.removeRow(tableStyle1.getSelectedRow());
        }
        else{
            if(tableStyle1.getSelectedRow() != -1){
                alterarpiloto = true;
                Piloto piloto = pilotos.get(tableStyle1.getSelectedRow());
                jTextField6.setText(piloto.getNome());
                jTextField2.setText(piloto.getCpf());
                jTextField5.setText(piloto.getTelefone());
                if(piloto.getHabilitacao().equals("Piloto Privado (PP)")){jComboBox2.setSelectedIndex(0);}
                else if(piloto.getHabilitacao().equals("Piloto Comercial (PC)")){jComboBox2.setSelectedIndex(1);}
                else{jComboBox2.setSelectedIndex(2);}
                myJButton1.setText("EXCLUIR");
                myJButton2.setText("CONFIRMAR");
            }
        }

    }//GEN-LAST:event_myJButton1ActionPerformed

    private void myJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myJButton2ActionPerformed
        if(alterarpiloto){
            alterarpiloto = false;
            Piloto piloto = pilotos.get(tableStyle1.getSelectedRow());

            piloto.setNome(jTextField6.getText());
            piloto.setCpf(jTextField2.getText());
            piloto.setTelefone(jTextField5.getText());
            piloto.setHabilitacao(jComboBox2.getSelectedItem().toString());
            
            jTextField2.setText(null);jTextField5.setText(null);jTextField6.setText(null);jComboBox2.setSelectedIndex(0);

            tableStyle1.setValueAt(piloto.getNome(), tableStyle1.getSelectedRow(), 0);
            tableStyle1.setValueAt(piloto.getCpf(), tableStyle1.getSelectedRow(), 1);
            tableStyle1.setValueAt(piloto.getTelefone(), tableStyle1.getSelectedRow(), 2);
            tableStyle1.setValueAt(piloto.getHabilitacao(), tableStyle1.getSelectedRow(), 3);

            myJButton1.setText("ALTERAR");
            myJButton2.setText("CADASTRAR");
        }
        else{
            if (jTextField2.getText().trim().isEmpty() && jTextField5.getText().trim().isEmpty() && jTextField6.getText().trim().isEmpty());
            else{
                Piloto novoPiloto = new Piloto(jTextField6.getText(), jTextField2.getText(),jTextField5.getText(),jComboBox2.getSelectedItem().toString());
                pilotos.add(novoPiloto);
                App.setPilotos(pilotos);

                DefaultTableModel mode = (DefaultTableModel) tableStyle1.getModel();
                mode.addRow(new Object[] {jTextField6.getText(), jTextField2.getText(),jTextField5.getText(),jComboBox2.getSelectedItem().toString()});
                jTextField2.setText(null);jTextField5.setText(null);jTextField6.setText(null);jComboBox2.setSelectedIndex(0);
            }            
        }

    }//GEN-LAST:event_myJButton2ActionPerformed

    private void myJButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myJButton3ActionPerformed
        PrimeiraTela.iniciar();
        this.dispose();
    }//GEN-LAST:event_myJButton3ActionPerformed


    private void myJButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myJButton4ActionPerformed
        if(alterarcomissario){
            alterarcomissario = false;
            comissarios.remove(tableStyle2.getSelectedRow());
            jTextField8.setText(null); jTextField3.setText(null); jTextField7.setText(null); jComboBox3.setSelectedIndex(0);
            myJButton4.setText("ALTERAR");
            myJButton5.setText("CADASTRAR");
            DefaultTableModel model = (DefaultTableModel) tableStyle2.getModel();
            model.removeRow(tableStyle2.getSelectedRow());
        }
        else{
            if(tableStyle2.getSelectedRow() != -1){
                alterarcomissario = true;
                Comissario comissario = comissarios.get(tableStyle2.getSelectedRow());
                jTextField8.setText(comissario.getNome());
                jTextField3.setText(comissario.getCpf());
                jTextField7.setText(comissario.getTelefone());

                myJButton4.setText("EXCLUIR");
                myJButton5.setText("CONFIRMAR");

                for (int c = 0; c < 12; c++){
                    if(comissario.getIdiomas().equals(jComboBox3.getItemAt(c).toString())){
                        jComboBox3.setSelectedIndex(c);
                        break;
                    }
                }
            }

            

        }
    }//GEN-LAST:event_myJButton4ActionPerformed

    private void myJButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myJButton5ActionPerformed
        if(alterarcomissario){
            alterarcomissario = false;
            Comissario comissario = comissarios.get(tableStyle2.getSelectedRow());

            comissario.setNome(jTextField8.getText());
            comissario.setCpf(jTextField3.getText());
            comissario.setTelefone(jTextField7.getText());
            comissario.setIdiomas(jComboBox3.getSelectedItem().toString());
            
            jTextField8.setText(null);jTextField3.setText(null);jTextField7.setText(null);jComboBox3.setSelectedIndex(0);

            tableStyle2.setValueAt(comissario.getNome(), tableStyle2.getSelectedRow(), 0);
            tableStyle2.setValueAt(comissario.getCpf(), tableStyle2.getSelectedRow(), 1);
            tableStyle2.setValueAt(comissario.getTelefone(), tableStyle2.getSelectedRow(), 2);
            tableStyle2.setValueAt(comissario.getIdiomas(), tableStyle2.getSelectedRow(), 3);

            myJButton4.setText("ALTERAR");
            myJButton5.setText("CADASTRAR");
        }
        else{
            if (jTextField3.getText().trim().isEmpty() && jTextField7.getText().trim().isEmpty() && jTextField8.getText().trim().isEmpty());
            else{
                Comissario novoComissario = new Comissario(jTextField8.getText(), jTextField3.getText(), jTextField7.getText(), jComboBox3.getSelectedItem().toString());
                comissarios.add(novoComissario);

                DefaultTableModel mode = (DefaultTableModel) tableStyle2.getModel();
                //Inserir valores na tabela
                mode.addRow(new Object[] {jTextField8.getText(), jTextField3.getText(),jTextField7.getText(),jComboBox3.getSelectedItem().toString()});
                jTextField3.setText(null);jTextField7.setText(null);jTextField8.setText(null);jComboBox3.setSelectedIndex(0);
            }            
        }

    }//GEN-LAST:event_myJButton5ActionPerformed

    private void myJButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myJButton6ActionPerformed
        PrimeiraTela.iniciar();
        this.dispose();
    }//GEN-LAST:event_myJButton6ActionPerformed

    private void buscarPiloto(){
        DefaultTableModel mode = (DefaultTableModel) tableStyle1.getModel();
        while(mode.getRowCount() != 0){
            mode.removeRow(0);
        }
        switch(jComboBox1.getSelectedIndex()){
            case 0:
                for (int c = 0; c < pilotos.size(); c++){
                    mode.addRow(new Object[] {pilotos.get(c).getNome(), pilotos.get(c).getCpf(), pilotos.get(c).getTelefone(), pilotos.get(c).getHabilitacao()});
                }
                break;
            case 1:
                for (int c = 0; c < pilotos.size(); c++){
                    try{
                        if(pilotos.get(c).getNome().substring(0, jTextField1.getText().length()).toUpperCase().equals(jTextField1.getText().toUpperCase())){
                            mode.addRow(new Object[] {pilotos.get(c).getNome(), pilotos.get(c).getCpf(), pilotos.get(c).getTelefone(), pilotos.get(c).getHabilitacao()});
                        }
                    }
                    catch(Exception e){}
                }
                break;
            case 2:
                for (int c = 0; c < pilotos.size(); c++){
                    try{
                        if(pilotos.get(c).getCpf().substring(0, jTextField1.getText().length()).equals(jTextField1.getText())){
                            mode.addRow(new Object[] {pilotos.get(c).getNome(), pilotos.get(c).getCpf(), pilotos.get(c).getTelefone(), pilotos.get(c).getHabilitacao()});
                        }
                    }
                    catch(Exception e){}
                }
                break;
            case 3:
                for (int c = 0; c < pilotos.size(); c++){
                    try{
                        if(pilotos.get(c).getTelefone().substring(0, jTextField1.getText().length()).equals(jTextField1.getText())){
                            mode.addRow(new Object[] {pilotos.get(c).getNome(), pilotos.get(c).getCpf(), pilotos.get(c).getTelefone(), pilotos.get(c).getHabilitacao()});
                        }                        
                    }
                    catch(Exception e){}

                }
                break;
            case 4:
                for (int c = 0; c < pilotos.size(); c++){
                    try{
                        if(pilotos.get(c).getHabilitacao().substring(0, jTextField1.getText().length()).toUpperCase().equals(jTextField1.getText().toUpperCase())){
                            mode.addRow(new Object[] {pilotos.get(c).getNome(), pilotos.get(c).getCpf(), pilotos.get(c).getTelefone(), pilotos.get(c).getHabilitacao()});
                        }                        
                    }
                    catch(Exception e){}
                }
                break;
        }
    }
    private void buscarComissario(){
        DefaultTableModel mode = (DefaultTableModel) tableStyle2.getModel();
        while(mode.getRowCount() != 0){
            mode.removeRow(0);
        }
        switch(jComboBox4.getSelectedIndex()){
            case 0:
                for (int c = 0; c < comissarios.size(); c++){
                    mode.addRow(new Object[] {comissarios.get(c).getNome(), comissarios.get(c).getCpf(), comissarios.get(c).getTelefone(), comissarios.get(c).getIdiomas()});
                }
                break;
            case 1:
                for (int c = 0; c < comissarios.size(); c++){
                    try{
                        if(comissarios.get(c).getNome().substring(0, jTextField4.getText().length()).toUpperCase().equals(jTextField4.getText().toUpperCase())){
                            mode.addRow(new Object[] {comissarios.get(c).getNome(), comissarios.get(c).getCpf(), comissarios.get(c).getTelefone(), comissarios.get(c).getIdiomas()});
                        }
                    }
                    catch(Exception e){}
                }
                break;
            case 2:
                for (int c = 0; c < comissarios.size(); c++){
                    try{
                        if(comissarios.get(c).getCpf().substring(0, jTextField4.getText().length()).equals(jTextField4.getText())){
                            mode.addRow(new Object[] {comissarios.get(c).getNome(), comissarios.get(c).getCpf(), comissarios.get(c).getTelefone(), comissarios.get(c).getIdiomas()});
                        }
                    }
                    catch(Exception e){}
                }
                break;
            case 3:
                for (int c = 0; c < pilotos.size(); c++){
                    try{
                        if(comissarios.get(c).getTelefone().substring(0, jTextField4.getText().length()).equals(jTextField4.getText())){
                            mode.addRow(new Object[] {comissarios.get(c).getNome(), comissarios.get(c).getCpf(), comissarios.get(c).getTelefone(), comissarios.get(c).getIdiomas()});
                        }                        
                    }
                    catch(Exception e){}

                }
                break;
            case 4:
                for (int c = 0; c < comissarios.size(); c++){
                    try{
                        if(comissarios.get(c).getIdiomas().substring(0, jTextField4.getText().length()).toUpperCase().equals(jTextField4.getText().toUpperCase())){
                            mode.addRow(new Object[] {comissarios.get(c).getNome(), comissarios.get(c).getCpf(), comissarios.get(c).getTelefone(), comissarios.get(c).getIdiomas()});
                        }                        
                    }
                    catch(Exception e){}
                }
                break;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void iniciar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManterFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManterFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManterFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManterFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                javax.swing.JFrame tela = new ManterFuncionario();
                tela.addWindowListener(new WindowAdapter() {
                    public void windowClosing(WindowEvent e){
                        App.serializar();
                    }
                });
                tela.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private MyJButton myJButton1;
    private MyJButton myJButton2;
    private MyJButton myJButton3;
    private MyJButton myJButton4;
    private MyJButton myJButton5;
    private MyJButton myJButton6;
    private TableStyle tableStyle1;
    private TableStyle tableStyle2;
    private ArrayList<Piloto> pilotos = App.getPilotos();
    private ArrayList<Comissario> comissarios = App.getComissarios();
    private boolean alterarcomissario = false;
    private boolean alterarpiloto = false;
    // End of variables declaration//GEN-END:variables
}
